int orient1D_x_00(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_y_00(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_z_00(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_x_01(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_y_01(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_z_01(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_x_10(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_y_10(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_z_10(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_x_11(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_y_11(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_z_11(const InputVertex &v0, const InputVertex &v1) const;
int orient1D_x_00(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_y_00(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_z_00(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_x_01(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_y_01(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_z_01(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_x_10(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_y_10(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_z_10(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_x_11(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_y_11(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_z_11(const InputVertex &v0, const VertexFromIntersection &v1) const;
int orient1D_x_00(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_y_00(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_z_00(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_x_01(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_y_01(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_z_01(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_x_10(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_y_10(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_z_10(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_x_11(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_y_11(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient1D_z_11(const VertexFromIntersection &v0, const VertexFromIntersection &v1) const;
int orient2D_x0_000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_y0_111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_z0_111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2) const;
int orient2D_x0_000(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_000(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_000(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_001(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_001(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_001(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_010(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_010(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_010(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_011(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_011(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_011(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_100(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_100(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_100(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_101(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_101(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_101(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_110(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_110(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_110(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_111(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_111(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_111(const InputVertex &v0, const InputVertex &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_000(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_000(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_000(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_001(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_001(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_001(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_010(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_010(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_010(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_011(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_011(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_011(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_100(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_100(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_100(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_101(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_101(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_101(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_110(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_110(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_110(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_111(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_111(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_111(const InputVertex &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_000(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_000(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_000(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_001(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_001(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_001(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_010(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_010(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_010(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_011(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_011(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_011(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_100(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_100(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_100(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_101(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_101(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_101(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_110(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_110(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_110(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_x0_111(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_y0_111(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient2D_z0_111(const VertexFromIntersection &v0, const VertexFromIntersection &v1, const VertexFromIntersection &v2) const;
int orient3D_0000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_1111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const InputVertex &v3) const;
int orient3D_0000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_0111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1000(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1001(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1010(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1011(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1100(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1101(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1110(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
int orient3D_1111(const InputVertex &v0, const InputVertex &v1, const InputVertex &v2, const VertexFromIntersection &v3) const;
